### ISSUE TITLE
Add ARGB support

### ISSUE THREAD

**Issue by Qix-** [Qix-/color-string#26]
Brought up over at Qix-/color#72 - some browsers support `#AARRGGBB`. This needs to be added here.

**Comment by Qix-** [comment]
Not sure we should support ARGB, but rather RGBA (I know IE uses ARGB but it's doing it wrong according to [the CSS4 specification](https://www.w3.org/TR/css-color-4/#hex-notation)). 

Turns out there is a 4 digit variant as well.

**Comment by halvves** [comment]
Hello @Qix- I've gone ahead and done this as RGBA to meet the css4 spec ([postcss/postcss-color-hex-alpha](https://github.com/postcss/postcss-color-hex-alpha) does this as well).
