### ISSUE TITLE
Round HSL strings?

### ISSUE THREAD

**Issue by ben-eb** [Qix-/color-string#29]
Previous versions of `color-string` rounded from RGB conversions.

So `0.3.0` for example converted `rgba(50%, 50%, 50%, 0.5)` to `hsla(0, 0%, 50%, 0.5)`, whereas in newer versions it outputs `hsla(0, 0%, 49.8%, 0.5)` instead.

Would it be possible to restore the previous behaviour?

**Comment by Qix-** [comment]
```javascript
myColor.hsl().string(0);
// or
myColor.round().hsl().string();
```

Since floating point HSL values are valid in CSS this was one I didn't automatically round to 0 (only RGB strings do).

**Comment by ben-eb** [comment]
Ah OK, thanks! `.round()` solves my issue. 😄
