### ISSUE TITLE
Color is failing when alpha is expressed in scientific notation

### ISSUE THREAD

**Issue by mapombo** [Qix-/color-string#30]
Color is failing when expressing the color-string alpha component using scientific notation.
A candidate fix could be redefining some of the regex'es to the following:

cs.get.rgb:
```javascript
var rgba = /^rgba?\(\s*([+-]?\d+)\s*,\s*([+-]?\d+)\s*,\s*([+-]?\d+)\s*(?:,\s*([+-]?[\d\.]+(e[+-]?\d+)?)\s*)?\)$/;
var per = /^rgba?\(\s*([+-]?[\d\.]+)\%\s*,\s*([+-]?[\d\.]+)\%\s*,\s*([+-]?[\d\.]+)\%\s*(?:,\s*([+-]?[\d\.]+(e[+-]?\d+))\s*)?\)$/;
```

cs.get.hsl:
```javascript
var hsl = /^hsla?\(\s*([+-]?\d*[\.]?\d+)(?:deg)?\s*,\s*([+-]?[\d\.]+)%\s*,\s*([+-]?[\d\.]+)%\s*(?:,\s*([+-]?[\d\.]+(e[+-]?\d+))\s*)?\)$/;
```

**Comment by Qix-** [comment]
As it should. Why are you expressing alpha values in scientific notation? It's not defined anywhere in the [CSS 4 specification](https://www.w3.org/TR/css-color-4/). You'll need to convert it to decimal notation.

Sorry, this isn't something I'll fix as there is no reason to (this library conforms to the w3 specification).

**Comment by Qix-** [comment]
I stand corrected. [It is defined by the spec](https://www.w3.org/TR/css3-values/#number-value).

Thanks for the bug report. I'll take a look at this module sometime this weekend. :)

**Comment by Qix-** [comment]
Added in `1.9.0`.
