### ISSUE TITLE
Printing `rgba`

### ISSUE THREAD

**Issue by idanen** [Qix-/color-string#35]
Is there a way to force the alpha to print in `rgb` even if the alpha is `1`?

**Comment by Qix-** [comment]
Not at the present moment. What's your use-case?

**Comment by idanen** [comment]
I'm currently changing the color library in our product, moving to [color](https://github.com/Qix-/color), and some service is expected to return `rgba` for all values.
We have a color picker that can edit the alpha so I guess it expects to always have an alpha.

**Comment by Qix-** [comment]
I know this is super late but I don't see this as a problem in this library. Either make the transformation yourself or open a ticket with the color picker you're using to assume an alpha of `1` if an `rgb()` string is presented.
