### ISSUE TITLE
Make case insensitive

### ISSUE THREAD

**Issue by benmccann** [Qix-/color-string#41]
`RGBA(45, 45, 45, 0.5);` should work as well as `rgba(45, 45, 45, 0.5);`

**Comment by Qix-** [comment]
Is this per specification? I'm away from my computer at the moment.

**Comment by benmccann** [comment]
The spec doesn't explicitly mention it in the section discussing `rgba`, but [elsewhere](https://www.w3.org/TR/css-color-4/#currentcolor-color) it mentions that "CSS keywords are case-insensitive"

CC @kurkle

**Comment by strarsis** [comment]
+1, could this be added?

**Comment by Qix-** [comment]
CSS keywords are the color keywords, that has nothing to do with `rgba()` et al.

I'd rather not deviate from the spec unless someone can find a definitive answer - call `.toLowerCase()` if you need to otherwise.
