### ISSUE TITLE
color-string incorrectly believes prototype properties are colors

### ISSUE THREAD

**Issue by tolmasky** [Qix-/color-string#44]
`color-string` will incorrectly return a color object for things like "constructor" and "\_\_proto\_\_".

Here is an example of all of them:

<img width="1000" alt="Screen Shot 2019-07-17 at 9 21 08 AM" src="https://user-images.githubusercontent.com/23753/61392698-43e0f600-a874-11e9-8330-c5383952c942.png">

https://runkit.com/tolmasky/color-string-prototype-bug

If one adds other properties to Object.prototype, those will also be mis-identified as colors.

**Comment by Qix-** [comment]
Great catch. Thanks for the repo, and sorry for the insane delay on this.
