### ISSUE TITLE
.to for including color model

### ISSUE THREAD

**Issue by strarsis** [Qix-/color-string#51]
For being able to preserve the original colors, it would be great if there is also a `to` method to which the parsed AST can be passed, resulting in the same model and value.

**Comment by Qix-** [comment]
Not quite sure what you mean, can you give an example?

**Comment by strarsis** [comment]
The `get` method returns an AST - now it should be possible to transform that AST back to a string.

**Comment by Qix-** [comment]
We do allow that, have you checked out the readme? :)

**Comment by strarsis** [comment]
Sure, one can use one of the to methods, like `hex` etc. But! The AST from the parser contains the `model`. Currently I have to check the `model` field and invoke the right `to` sub-method in order to get the same string as before.

**Comment by Qix-** [comment]
Hmm, does `cs.to[color.model](color)` not work?

**Comment by strarsis** [comment]
@Qix-: It could! But it would be nice if there is an official method that can be used without relying on method-name-model-parity.

**Comment by Qix-** [comment]
I disagree here, there wouldn't be much worth in my opinion. The model should always be the same, thus the function you're describing would do literally `cs.to[color.model](color)`. Nothing more.

I don't see much benefit in adding this as an extra API function - this is quite trivial to do. Thanks for the idea, though :)
