### ISSUE TITLE
Version 1.7.x generate broken var(--white)

### ISSUE THREAD

**Issue by iurisilvio** [Qix-/color-string#60]
After today upgrade, my nuxt app replaced `var(--white)` with `var(#fff)`, which generated broken CSS.

I have 
```
:root {
    --white: #ffffff;
}
```

Version 1.7.0 works fine, versions 1.7.1 and 1.7.4 are broken. I didn't tested with 1.7.2 and 1.7.3, but I expect the same issue there.

**Comment by Qix-** [comment]
This seems like a bug in Nuxt. We don't check for `var()`. Please open an issue with them as they might be mis-using this library.

**Comment by iurisilvio** [comment]
The same project works with version 1.7.0 and fails with 1.7.1, it's definitely related with color-string.

**Comment by Qix-** [comment]
That's not a given. You shouldn't be passing in `var()` to this library, so clearly you're mis-using it. If you were relying on a bug (in this case, unspecified input) prior to the bugfixes going out, that's not my problem. Sorry.

If you're using a framework that wraps this library, please open an issue with the framework maintainers. Nothing I've changed here today breaks the specified API of this library.
