### ISSUE TITLE
rgb with only two params incorrectly parse color

### ISSUE THREAD

**Issue by gerdasi** [Qix-/color-string#65]
Hey!

I'm using `color` package and have some local tests for invalid user input check. After recent release (`4.0.2`) couple of my tests started failing. 
Previously `rgb(255,2)` color was invalid and now it returns `[25, 5, 2]`. 
The same goes for `rgba(255,0)`  - it returns `[25, 5, 0]`.

Is this expected behaviour? As far as I know, it should be invalid syntax 🤔 . 
Thanks! 🙏

**Comment by Qix-** [comment]
Thanks for the report, sorry about that! Fix landed in 32f3e0092ffbe78f4dd7886dd1f225b114fb1a7b, released as `1.8.2`.

**Comment by mastertheblaster** [comment]
Thanks, seems it fixed the problem 💯

**Comment by Qix-** [comment]
No problem, thanks for confirming!

**Comment by gerdasi** [comment]
Thank you! 🎊
